"""
Configuration module for the Smart Nutrition Recommendation System.
Centralizes all constants, reference ranges, and system settings.
"""

import os
from dotenv import load_dotenv

load_dotenv(override=True)

# ─── Flask Settings ───────────────────────────────────────────────
SECRET_KEY = os.getenv("SECRET_KEY", "change-me-in-production")
UPLOAD_FOLDER = os.path.join(os.path.dirname(os.path.dirname(__file__)), "uploads")
ALLOWED_EXTENSIONS = {"pdf", "png", "jpg", "jpeg"}
MAX_CONTENT_LENGTH = 16 * 1024 * 1024  # 16 MB

# ─── Gemini API ───────────────────────────────────────────────────
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# ─── Biomarker Reference Ranges ──────────────────────────────────
# Format: (low_normal, high_normal, unit, critical_low, critical_high)
BIOMARKER_RANGES = {
    "hemoglobin":          {"low": 12.0, "high": 17.5, "unit": "g/dL",   "critical_low": 7.0,   "critical_high": 20.0},
    "glucose":             {"low": 70,   "high": 100,  "unit": "mg/dL",  "critical_low": 40,    "critical_high": 400},
    "hba1c":               {"low": 4.0,  "high": 5.6,  "unit": "%",      "critical_low": None,  "critical_high": 10.0},
    "ldl":                 {"low": 0,    "high": 100,  "unit": "mg/dL",  "critical_low": None,  "critical_high": 190},
    "hdl":                 {"low": 40,   "high": 60,   "unit": "mg/dL",  "critical_low": 20,    "critical_high": None},
    "total_cholesterol":   {"low": 0,    "high": 200,  "unit": "mg/dL",  "critical_low": None,  "critical_high": 300},
    "triglycerides":       {"low": 0,    "high": 150,  "unit": "mg/dL",  "critical_low": None,  "critical_high": 500},
    "vitamin_d":           {"low": 30,   "high": 100,  "unit": "ng/mL",  "critical_low": 10,    "critical_high": 150},
    "vitamin_b12":         {"low": 200,  "high": 900,  "unit": "pg/mL",  "critical_low": 100,   "critical_high": None},
}

# ─── Health Classification Thresholds ────────────────────────────
RISK_CATEGORIES = {
    "Low Risk":      {"label": "Low Risk",      "color": "success"},
    "Moderate Risk": {"label": "Moderate Risk",  "color": "warning"},
    "High Risk":     {"label": "High Risk",      "color": "danger"},
}

# ─── Nutrient Daily Reference Intakes ────────────────────────────
NUTRIENT_RDI = {
    "calories":      {"unit": "kcal", "min": 1500, "max": 3000},
    "protein":       {"unit": "g",    "min": 46,   "max": 150},
    "carbohydrates": {"unit": "g",    "min": 200,  "max": 400},
    "fat":           {"unit": "g",    "min": 44,   "max": 100},
    "fiber":         {"unit": "g",    "min": 25,   "max": 40},
    "iron":          {"unit": "mg",   "min": 8,    "max": 45},
    "calcium":       {"unit": "mg",   "min": 1000, "max": 2500},
    "vitamin_d":     {"unit": "IU",   "min": 600,  "max": 4000},
    "vitamin_b12":   {"unit": "mcg",  "min": 2.4,  "max": 100},
    "omega_3":       {"unit": "g",    "min": 1.1,  "max": 4},
}

# ─── Medical Disclaimer ──────────────────────────────────────────
MEDICAL_DISCLAIMER = (
    "DISCLAIMER: This report is generated by an AI system for informational "
    "purposes only and does NOT constitute medical advice, diagnosis, or treatment. "
    "Always consult a qualified healthcare professional before making any changes "
    "to your diet, medication, or lifestyle. Do not disregard professional medical "
    "advice or delay seeking it because of information provided by this system."
)
